spring:
  application:
    name: "Transmatter Platform Administration Subsystem"
  profiles:
    active:
      - db
  datasource:
    url: jdbc:postgresql://db.oviyqdunqfzeqakjynkh.supabase.co:5432/postgres?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: Tmat@501739
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    username: transmatter.team@outlook.com
    password: Tmat@1739
    host: smtp-mail.outlook.com
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp-mail.outlook.com
          auth: false
    port: 587
  data:
    mongodb:
      uri: mongodb+srv://oat:JustOat5039@cluster0.wj65o.mongodb.net
      database: mock_remote_data
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
    register:
      path: registers
      refresh: refresh
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: false

